apiVersion: v1
kind: Secret
metadata:
  name: kibana-service-token
  namespace: logging
type: Opaque
stringData:
  token: "AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS1naXRvcHM6amE3TXhlMVhRSUdFTkRTMjFvU1RWdw"

