apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-elasticsearch
  namespace: argocd
spec:
  project: default
  destination:
    namespace: logging
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://helm.elastic.co
      chart: elasticsearch
      targetRevision: 8.x
      helm:
        values: |
          replicas: 1
          minimumMasterNodes: 1
          antiAffinity: "soft"
          esConfig:
            elasticsearch.yml: |
              xpack.security.enabled: true
              xpack.security.http.ssl.enabled: true
              xpack.security.transport.ssl.enabled: true
    - repoURL: https://github.com/tziyon31/demo-crm-gitops.git
      targetRevision: main
      path: infra/elasticsearch
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: elasticsearch-master-credentials
      namespace: logging
      jqPathExpressions:
        - .data
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
