apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-kibana
  namespace: argocd
spec:
  project: default
  destination:
    namespace: logging
    server: https://kubernetes.default.svc
  source:
    repoURL: https://helm.elastic.co
    chart: kibana
    targetRevision: "8.5.1"
    helm:
      values: |
        elasticsearchHosts:
          - "https://elasticsearch-master.logging.svc.cluster.local:9200"

        kibanaConfig:
          kibana.yml: |
            elasticsearch.ssl.verificationMode: none

        extraEnvs:
          - name: ELASTICSEARCH_USERNAME
            value: "elastic"
          - name: ELASTICSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                name: elasticsearch-master-credentials
                key: password

        serviceAccount:
          create: false
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
