apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-mongodb-operator
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-crm
  source:
    repoURL: git@github.com:tziyon31/demo-crm-gitops.git
    targetRevision: main
    path: infra-apps/charts/community-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

