apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-kibana
  namespace: argocd
spec:
  project: default

  destination:
    namespace: logging
    server: https://kubernetes.default.svc

  source:
    repoURL: https://helm.elastic.co
    chart: kibana
    targetRevision: "*"
    helm:
      values: |
        elasticsearchHosts: "http://elasticsearch-master.logging.svc.cluster.local:9200"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
