apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-elasticsearch
  namespace: argocd
spec:
  project: default
  destination:
    namespace: logging
    server: https://kubernetes.default.svc
  source:
    repoURL: https://helm.elastic.co
    chart: elasticsearch
    targetRevision: 8.x
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
