apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-fluentbit
  namespace: argocd
spec:
  project: default

  destination:
    namespace: logging
    server: https://kubernetes.default.svc

  source:
    repoURL: git@github.com:tziyon31/demo-crm-gitops.git
    targetRevision: main
    path: infra-apps/charts/fluent-bit

  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

