apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-kibana
  namespace: argocd
  annotations:
    
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: logging

  source:
    repoURL: https://github.com/tziyon31/demo-crm-gitops.git
    targetRevision: main
    path: infra-apps/charts/kibana
    helm:
      valueFiles:
        - values.yaml

  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

