apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-fluentbit
  namespace: argocd
spec:
  project: default
  destination:
    namespace: logging
    server: https://kubernetes.default.svc
  source:
    repoURL: https://fluent.github.io/helm-charts
    chart: fluent-bit
    targetRevision: "*"
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
