apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-namespaces
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/tziyon31/demo-crm-gitops.git
    targetRevision: main
    path: infra-apps/manifests/namespaces
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

