apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-apps
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    repoURL: https://github.com/tziyon31/demo-crm-gitops.git
    targetRevision: main
    path: apps
    directory:
      recurse: false
      include: '{infra-root.yaml,demo-crm-helm.yaml}'
  syncPolicy:
    automated:
      selfHeal: true
      # prune: false  
    syncOptions:
      - CreateNamespace=true

