apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-crm-juice-shop
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: juice-shop

  sources:
    - repoURL: https://charts.securecodebox.io
      chart: juice-shop
      targetRevision: 5.5.0
      helm:
        valueFiles:
          - $values/infra-apps/values/juice-shop/values.yaml
    - repoURL: https://github.com/tziyon31/demo-crm-gitops.git
      targetRevision: main
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
