apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-crm-helm
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-crm
  source:
    repoURL: git@github.com:tziyon31/demo-crm-helm.git
    targetRevision: main
    path: .
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

